import json
import numpy as np
from ..utils import _path
from .. import frustration
from .Structure import Structure, SparseMatrix
from .Frustratometer import Frustratometer
from .Gamma import Gamma
from pydantic import BaseModel, Field, ConfigDict
from pydantic.types import Path
from typing import List,Optional,Union

__all__ = ['AWSEM']


class AWSEMParameters(BaseModel):
    model_config = ConfigDict(extra='ignore', arbitrary_types_allowed=True)
    """Default parameters for AWSEM energy calculations."""
    k_contact: float = Field(4.184, description="Coefficient for contact potential. (kJ/mol)")
    
    #Density
    eta: float = Field(5.0, description="Sharpness of the distance-based switching function (Angstrom^-1).")
    rho_0: float = Field(2.6, description="Density cutoff defining buried residues.")
    min_sequence_separation_rho: Optional[int] = Field(2, description="Minimum sequence separation for density calculation.")

    #Burial potential
    burial_in_context: Optional[bool] = Field(True, description="For substructure objects, this may include interactions from remainder of protein in burial term.")
    burial_kappa: float = Field(4.0, description="Sharpness of the density-based switching function for the burial potential wells")
    burial_ro_min: List[float] = Field([0.0, 3.0, 6.0], description="Minimum radii for burial potential wells. (Angstrom)")
    burial_ro_max: List[float] = Field([3.0, 6.0, 9.0], description="Maximum radii for burial potential wells. (Angstrom)")
    
    #Direct contacts
    min_sequence_separation_contact: Optional[int] = Field(0, description="Minimum sequence separation for contact calculation.")
    distance_cutoff_contact: Optional[float] = Field(9.5, description="Distance cutoff for contact calculation. (Angstrom)")
    r_min: float = Field(4.5, description="Minimum distance for direct contact potential. (Angstrom)")
    r_max: float = Field(6.5, description="Maximum distance for direct contact potential. (Angstrom)")
    
    #Mediated contacts
    gamma: Union[Path,Gamma] = Field(_path/'data'/'AWSEM_2015.json', description="File or Gamma object containing the Gamma values")
    r_minII: float = Field(6.5, description="Minimum distance for mediated contact potential. (Angstrom)")
    r_maxII: float = Field(9.5, description="Maximum distance for mediated contact potential. (Angstrom)")
    eta_sigma: float = Field(7.0, description="Sharpness of the density-based switching function between protein-mediated and water-mediated contacts.")
    

    #Membrane
    membrane: bool = Field(False, description="Enable membrane-aware energy calculation.")
    membrane_gamma: Union[Path,Gamma] = Field(_path/'data'/'AWSEM_membrane_2015.json', description="File or Gamma object containing the membrane Gamma values (for membrane proteins)")
    eta_switching: float = Field(1.0, description="Sharpness of the alpha switching function for membrane contact blending (Angstrom^-1).")
    z_m: float = Field(15.0, description="Membrane half-thickness (Angstrom).")
    z_source: str = Field("Auto", description="Atom name used for membrane Z-coordinate reference (e.g. Auto, CB or CA).")
    membrane_center: float = Field(0.0, description="Z-coordinate of membrane center (Angstrom).")
    k_membrane: float = Field(4.184, description="Strength of Zim membrane potential (kJ/mol).")
    k_m: float = Field(2.0, description="Sharpness of Zim boundary switching function (Angstrom^-1).")
    k_relative_mem: float = Field(1.0, description="Scalar multiplier for membrane gamma matrices (amplifies membrane contact interactions).")
    zim: Optional[List[float]] = Field(None, description="Per-residue hydrophobicity values (DGwoct). If None, computed from Wimley-White scale.")

    #Electrostatics
    min_sequence_separation_electrostatics: Optional[int] = Field(1, description="Minimum sequence separation for electrostatics calculation.")
    k_electrostatics: float = Field(17.3636, description="Coefficient for electrostatic interactions. (kJ/mol)")
    electrostatics_screening_length: float = Field(10, description="Screening length for electrostatic interactions. (Angstrom)")

class AWSEM(Frustratometer):
    #Mapping to DCA
    q = 20
    aa_map_awsem_list = [0, 0, 4, 3, 6, 13, 7, 8, 9, 11, 10, 12, 2, 14, 5, 1, 15, 16, 19, 17, 18] #A gap has no energy
    aa_map_awsem_x, aa_map_awsem_y = np.meshgrid(aa_map_awsem_list, aa_map_awsem_list, indexing='ij')
    
    def __init__(self, 
                 pdb_structure: Structure,
                 sequence: Union[str, None] =None,
                 expose_indicator_functions: bool=False,
                 sparse: bool=True,
                 **parameters):
        """
        Generate AWSEM object

        Parameters
        ----------
        pdb_structure : object
            Structure object generated by Structure class
        sequence :  str
            The amino acid sequence of the protein. The sequence is assumed to be in one-letter code. 
        expose_indicator_functions: bool
            If set to True, indicator functions of the contact and burial energy terms can be accessed by user.
        sparse : bool
            If True (default), build a sparse Potts model storing couplings only at contact positions,
            avoiding the dense (N, N, Q, Q) meshgrid. If False, build the full dense representation.
        
        Returns
        -------
        AWSEM object
        """
        
        #Set attributes
        p = AWSEMParameters(**parameters)
        if p.min_sequence_separation_contact is None:
            p.min_sequence_separation_contact = 1
        if p.min_sequence_separation_rho is None:
            p.min_sequence_separation_rho = 1
        if p.min_sequence_separation_electrostatics is None:
            p.min_sequence_separation_electrostatics = 1

        for field, value in p:
            setattr(self, field, value)
        
        #Gamma parameters
        if isinstance(p.gamma, Gamma):
            gamma = p.gamma
        elif isinstance(p.gamma, (Path, str)):
            gamma_path = Path(p.gamma)
            local_candidate = Path.cwd() / p.gamma
            if local_candidate.exists():   
                gamma_path = local_candidate
            elif gamma_path.suffix == '' and gamma_path.parent == Path('.'):
                data_candidate = _path / 'data' / p.gamma.with_suffix('.json')
                if data_candidate.exists():
                    gamma_path = data_candidate
                else:
                    raise FileNotFoundError(f"Did not found the gamma file: {str(data_candidate)}")
            else:
                raise FileNotFoundError(f"Did not found the gamma file: {p.gamma}")
            gamma = Gamma(gamma_path)
        else:
            raise ValueError("Gamma parameter must be a path or a Gamma object.")
                
        self.gamma=gamma
        self.burial_gamma = gamma['Burial'].T
        self.direct_gamma = gamma['Direct'][0]
        self.protein_gamma = gamma['Protein'][0]
        self.water_gamma = gamma['Water'][0]
        self.burial_in_context=p.burial_in_context

        # Membrane gamma loading
        if p.membrane:
            if isinstance(p.membrane_gamma, Gamma):
                membrane_gamma_obj = p.membrane_gamma
            elif isinstance(p.membrane_gamma, Path):
                membrane_gamma_obj = Gamma(p.membrane_gamma)
            else:
                raise ValueError("membrane_gamma parameter must be a path or a Gamma object.")
            self.membrane_burial_gamma = membrane_gamma_obj['Burial'].T
            self.membrane_direct_gamma = membrane_gamma_obj['Direct'][0] * p.k_relative_mem
            self.membrane_protein_gamma = membrane_gamma_obj['Protein'][0] * p.k_relative_mem
            self.membrane_water_gamma = membrane_gamma_obj['Water'][0] * p.k_relative_mem

        #Structure details
        self.full_to_aligned_index_dict=pdb_structure.full_to_aligned_index_dict
        if sequence is None:
            self.sequence=pdb_structure.sequence
        else:
            self.sequence=sequence
        self.structure=pdb_structure.structure
        self.chain=pdb_structure.chain
        self.pdb_file=pdb_structure.pdb_file
        self.init_index_shift=pdb_structure.init_index_shift
        self.distance_matrix=pdb_structure.distance_matrix
        self.full_pdb_distance_matrix=pdb_structure.full_pdb_distance_matrix
        self.chain_breaks=pdb_structure.chain_breaks
        self._distance_is_sparse = pdb_structure._is_sparse
        #Sparse matrices
        self._sparse_distance_matrix = None
        self._sparse_distance_matrix_elec = None
        if self._distance_is_sparse:
            self._sparse_distance_matrix = pdb_structure._sparse_distance_matrix
            self._sparse_distance_matrix_elec = pdb_structure._sparse_distance_matrix_elec
            if not sparse:
                # Dense Potts model from sparse distances.
                from frustratometer.pdb import distance as _pdb_dist
                dense_dm = _pdb_dist.get_dense_distance_matrix(
                    pdb_file=pdb_structure.pdb_file,
                    chain=pdb_structure.chain,
                    method=pdb_structure.distance_matrix_method)
                if pdb_structure.seq_selection is not None:
                    dense_dm = dense_dm[
                        pdb_structure.init_index_shift:pdb_structure.fin_index_shift,
                        pdb_structure.init_index_shift:pdb_structure.fin_index_shift]
                self.distance_matrix = dense_dm
                self.full_pdb_distance_matrix = dense_dm
                self._distance_is_sparse = False
        else:
            self._sparse_distance_matrix = None
            self._sparse_distance_matrix_elec = None
        selection_CA = self.structure.select('name CA')
        selection_CB = self.structure.select('name CB or (resname GLY IGL and name CA)')

        resid = selection_CB.getResindices()
        self.resid=resid
        self.N=len(self.resid)
        assert self.N == len(self.sequence), "The pdb is incomplete. Try setting 'repair_pdb=True' when constructing the Structure object."

        # Membrane alpha and phi_z computation
        if p.membrane:
            # OpenAWSEM has two membrane Zim behaviors:
            # - membrane_preassigned_term: CB (or CA fallback)
            # - membrane_term (simple, no preassigned file): CA
            # May need to adjust in the future to set custom z_source
            if p.z_source == "Auto":
                z_source = selection_CB if p.zim is not None else selection_CA
            elif p.z_source == "CB":
                z_source = selection_CB
            elif p.z_source == "CA":
                z_source = selection_CA
            else:
                raise ValueError(f"Invalid z_source value: {p.z_source}. Must be 'Auto', 'CB', or 'CA'.")
            z_coords = z_source.getCoords()[:, 2] - p.membrane_center
            self.z_coords = z_coords
            # alpha_i ≈ 1 inside membrane, ≈ 0 outside
            self.alpha = 0.5 * np.tanh(p.eta_switching * (z_coords + p.z_m)) + 0.5 * np.tanh(p.eta_switching * (p.z_m - z_coords))
            # phi_z for Zim potential (same shape but sharper boundary via k_m)
            self.phi_z = 0.5 * np.tanh(p.k_m * (z_coords + p.z_m)) + 0.5 * np.tanh(p.k_m * (p.z_m - z_coords))
            # Per-residue DGwoct values
            # Load Wimley-White DGwoct scale (20 values in AWSEM aa order)
            _AA = 'ARNDCQEGHILKMFPSTWYV'
            with open(_path / 'data' / 'wimley_white_dgwoct.json') as f:
                ww = json.load(f)
            self._dgwoct_scale = np.array(ww['DGwoct'], dtype=np.float64)  # (20,)
            if p.zim is not None:
                self.dgwoct = np.array(p.zim, dtype=np.float64)
            else:
                self.dgwoct = np.array([self._dgwoct_scale[_AA.index(aa)] for aa in self.sequence], dtype=np.float64)
        else:
            self.alpha = None
            self.phi_z = None
            self.dgwoct = None
            self.z_coords = None
            self._dgwoct_scale = None

        self._decoy_fluctuation = {}
        self.minimally_frustrated_threshold=.78

        if self._distance_is_sparse:
            self._init_from_sparse_distances(p, sparse, expose_indicator_functions, pdb_structure)
        else:
            self._init_from_dense_distances(p, sparse, expose_indicator_functions, pdb_structure)

    def _init_from_sparse_distances(self, p, sparse, expose, pdb_structure):
        """Initialize AWSEM physics from sparse COO distance data (no L×L arrays)."""
        dm = self._sparse_distance_matrix

        # --- Rho computation ---
        if self.burial_in_context:
            full_dm = self.full_pdb_distance_matrix
            if isinstance(full_dm, SparseMatrix):
                sel_dm = full_dm
            else:
                # Full PDB is dense but selection is sparse — fallback
                sel_dm = dm
        else:
            sel_dm = dm

        # Rho sequence separation mask
        rho_mask = frustration.compute_mask_sparse(
            sel_dm.row, sel_dm.col, sel_dm.data, sel_dm.shape,
            maximum_contact_distance=None,
            minimum_sequence_separation=p.min_sequence_separation_rho,
            chain_breaks=self.chain_breaks)
        rho_dists = sel_dm.lookup(rho_mask.row, rho_mask.col)

        rho_vals = 0.25 * (1 + np.tanh(p.eta * (rho_dists - p.r_min))) * (1 + np.tanh(p.eta * (p.r_max - rho_dists)))
        rho_r = np.bincount(rho_mask.row, weights=rho_vals, minlength=sel_dm.shape).astype(np.float64)

        # Handle burial_in_context substructure slicing
        if sel_dm.shape != dm.shape and self.burial_in_context:
            self.init_index_shift = pdb_structure.init_index_shift
            self.fin_index_shift = pdb_structure.fin_index_shift
            rho_r = rho_r[self.init_index_shift:self.fin_index_shift]

        self.rho = None  # No dense rho matrix in sparse mode
        self.rho_r = rho_r

        # --- Contact mask ---
        contact_mask = frustration.compute_mask_sparse(
            dm.row, dm.col, dm.data, dm.shape,
            maximum_contact_distance=p.distance_cutoff_contact,
            minimum_sequence_separation=p.min_sequence_separation_contact,
            chain_breaks=self.chain_breaks)
        contact_dists = dm.lookup(contact_mask.row, contact_mask.col)

        # Theta/thetaII at contacts only
        theta_c = 0.25 * (1 + np.tanh(p.eta * (contact_dists - p.r_min))) * (1 + np.tanh(p.eta * (p.r_max - contact_dists)))
        thetaII_c = 0.25 * (1 + np.tanh(p.eta * (contact_dists - p.r_minII))) * (1 + np.tanh(p.eta * (p.r_maxII - contact_dists)))

        # Sigma at contact positions (no L×L allocation)
        sigma_water_c = 0.25 * (1 - np.tanh(p.eta_sigma * (rho_r[contact_mask.row] - p.rho_0))) * (1 - np.tanh(p.eta_sigma * (rho_r[contact_mask.col] - p.rho_0)))
        sigma_protein_c = 1 - sigma_water_c

        # Store None for dense sigma (used in configurational frustration)
        self._sigma_water = None
        self._sigma_protein = None

        # --- Burial ---
        rho_b = np.expand_dims(rho_r, 1)
        burial_indicator = np.tanh(p.burial_kappa * (rho_b - p.burial_ro_min)) + np.tanh(p.burial_kappa * (p.burial_ro_max - rho_b))
        self._burial_indicator = burial_indicator

        h_index = np.meshgrid(range(self.N), range(self.q), indexing='ij', sparse=False)
        burial_energy = 0.5 * p.k_contact * self.burial_gamma[h_index[1]] * burial_indicator[:, np.newaxis, :]
        self.burial_energy = burial_energy

        # --- Main mask (sparse) ---
        if p.k_electrostatics != 0:
            self.sequence_cutoff = min(p.min_sequence_separation_electrostatics, p.min_sequence_separation_contact)
            self.distance_cutoff = None
        else:
            self.sequence_cutoff = p.min_sequence_separation_contact
            self.distance_cutoff = p.distance_cutoff_contact
        mask_result = frustration.compute_mask_sparse(
            dm.row, dm.col, dm.data, dm.shape,
            maximum_contact_distance=self.distance_cutoff,
            minimum_sequence_separation=self.sequence_cutoff,
            chain_breaks=self.chain_breaks)
        self.mask = mask_result

        # Common properties
        self.aa_freq = frustration.compute_aa_freq(self.sequence)
        self.contact_freq = frustration.compute_contact_freq(self.sequence)

        # Build sparse Potts model (always sparse when distance is sparse)
        self._build_sparse_from_contacts(p, contact_mask.row, contact_mask.col, theta_c, thetaII_c,
                                         sigma_water_c, sigma_protein_c, burial_energy, expose)

    def _init_from_dense_distances(self, p, sparse, expose, pdb_structure):
        """Initialize AWSEM physics from dense distance matrix (original path)."""
        if self.burial_in_context==True:
            selected_matrix=self.full_pdb_distance_matrix
        else:
            selected_matrix=self.distance_matrix
        sequence_mask_rho = frustration.compute_mask(selected_matrix,
                                                     maximum_contact_distance=None,
                                                     minimum_sequence_separation = p.min_sequence_separation_rho,
                                                     chain_breaks=self.chain_breaks)
        sequence_mask_contact = frustration.compute_mask(self.distance_matrix,
                                                     maximum_contact_distance=p.distance_cutoff_contact,
                                                     minimum_sequence_separation = p.min_sequence_separation_contact,
                                                     chain_breaks=self.chain_breaks)

        # Calculate rho
        rho = 0.25
        rho *= (1 + np.tanh(p.eta * (selected_matrix- p.r_min)))
        rho *= (1 + np.tanh(p.eta * (p.r_max - selected_matrix)))
        rho *= sequence_mask_rho
        self.rho=rho

        #Calculate sigma water
        rho_r = (rho).sum(axis=1)
        if self.full_pdb_distance_matrix.shape!=self.distance_matrix.shape:
            if self.burial_in_context==True:
                self.init_index_shift=pdb_structure.init_index_shift
                self.fin_index_shift=pdb_structure.fin_index_shift
                rho_r=rho_r[self.init_index_shift:self.fin_index_shift]
        self.rho_r=rho_r
        rho_b = np.expand_dims(rho_r, 1)
        rho1 = np.expand_dims(rho_r, 0)
        rho2 = np.expand_dims(rho_r, 1)
        sigma_water = 0.25 * (1 - np.tanh(p.eta_sigma * (rho1 - p.rho_0))) * (1 - np.tanh(p.eta_sigma * (rho2 - p.rho_0)))
        sigma_protein = 1 - sigma_water

        #Calculate theta and indicators
        theta = 0.25 * (1 + np.tanh(p.eta * (self.distance_matrix - p.r_min))) * (1 + np.tanh(p.eta * (p.r_max - self.distance_matrix)))
        thetaII = 0.25 * (1 + np.tanh(p.eta * (self.distance_matrix - p.r_minII))) * (1 + np.tanh(p.eta * (p.r_maxII - self.distance_matrix)))
        burial_indicator = np.tanh(p.burial_kappa * (rho_b - p.burial_ro_min)) + np.tanh(p.burial_kappa * (p.burial_ro_max - rho_b))
        self._burial_indicator = burial_indicator
        self._sigma_water = sigma_water
        self._sigma_protein = sigma_protein

        # Burial energy
        h_index = np.meshgrid(range(self.N), range(self.q), indexing='ij', sparse=False)
        burial_energy = 0.5 * p.k_contact * self.burial_gamma[h_index[1]] * burial_indicator[:, np.newaxis, :]
        self.burial_energy = burial_energy

        # Electrostatics-aware mask
        if p.k_electrostatics != 0:
            self.sequence_cutoff = min(p.min_sequence_separation_electrostatics, p.min_sequence_separation_contact)
            self.distance_cutoff = None
        else:
            self.sequence_cutoff = p.min_sequence_separation_contact
            self.distance_cutoff = p.distance_cutoff_contact
        self.mask = frustration.compute_mask(self.distance_matrix, maximum_contact_distance=self.distance_cutoff, minimum_sequence_separation=self.sequence_cutoff, chain_breaks=self.chain_breaks)

        # Common properties
        self.aa_freq = frustration.compute_aa_freq(self.sequence)
        self.contact_freq = frustration.compute_contact_freq(self.sequence)

        # Build Potts model
        if sparse:
            self._build_sparse(p, sequence_mask_contact, theta, thetaII, burial_energy, expose)
        else:
            self._build_dense(p, sequence_mask_contact, theta, thetaII, burial_energy, expose)

    def _start_indicator_exposure(self, p):
        """Set up burial indicators and gamma arrays (common to sparse and dense)."""
        burial_indicator = self._burial_indicator

        # Burial indicators and gammas are the same regardless of membrane flag
        self.indicators = [burial_indicator[:, 0], burial_indicator[:, 1], burial_indicator[:, 2]]

        temp_burial_gamma = self.burial_gamma[self.aa_map_awsem_list].copy()
        temp_burial_gamma[0] = 0
        temp_burial_gamma *= -0.5 * p.k_contact
        self.gamma_array = [temp_burial_gamma[:, 0], temp_burial_gamma[:, 1], temp_burial_gamma[:, 2]]

        if p.membrane:
            # Add phi_z indicator and zim gamma
            zim_gamma = p.k_membrane * self._dgwoct_scale[self.aa_map_awsem_list].copy()
            zim_gamma[0] = 0
            self.indicators.append(self.phi_z)
            self.gamma_array.append(zim_gamma)

            # Water contact gammas
            for contact_gamma in [self.direct_gamma, self.protein_gamma, self.water_gamma]:
                temp_gamma = contact_gamma[self.aa_map_awsem_x, self.aa_map_awsem_y].copy()
                temp_gamma[0, :] = 0
                temp_gamma[:, 0] = 0
                temp_gamma *= -0.5 * p.k_contact
                self.gamma_array.append(temp_gamma)
            # Membrane contact gammas
            for contact_gamma in [self.membrane_direct_gamma, self.membrane_protein_gamma, self.membrane_water_gamma]:
                temp_gamma = contact_gamma[self.aa_map_awsem_x, self.aa_map_awsem_y].copy()
                temp_gamma[0, :] = 0
                temp_gamma[:, 0] = 0
                temp_gamma *= -0.5 * p.k_contact
                self.gamma_array.append(temp_gamma)
        else:
            for contact_gamma in [self.direct_gamma, self.protein_gamma, self.water_gamma]:
                temp_gamma = contact_gamma[self.aa_map_awsem_x, self.aa_map_awsem_y].copy()
                temp_gamma[0, :] = 0
                temp_gamma[:, 0] = 0
                temp_gamma *= -0.5 * p.k_contact
                self.gamma_array.append(temp_gamma)

    def _build_dense(self, p, sequence_mask_contact, theta, thetaII, burial_energy, expose):
        """Build dense Potts model with full (N, N, Q, Q) coupling tensors."""
        sigma_water = self._sigma_water
        sigma_protein = self._sigma_protein

        # 4D indicators
        direct_indicator = theta[:, :, np.newaxis, np.newaxis]
        water_indicator = thetaII[:, :, np.newaxis, np.newaxis] * sigma_water[:, :, np.newaxis, np.newaxis]
        protein_indicator = thetaII[:, :, np.newaxis, np.newaxis] * sigma_protein[:, :, np.newaxis, np.newaxis]

        # Contact energy
        J_index = np.meshgrid(range(self.N), range(self.N), range(self.q), range(self.q), indexing='ij', sparse=False)
        direct = direct_indicator * self.direct_gamma[J_index[2], J_index[3]]
        water_mediated = water_indicator * self.water_gamma[J_index[2], J_index[3]]
        protein_mediated = protein_indicator * self.protein_gamma[J_index[2], J_index[3]]
        contact_energy_water = p.k_contact * np.array([direct, water_mediated, protein_mediated]) * sequence_mask_contact[np.newaxis, :, :, np.newaxis, np.newaxis]

        if p.membrane:
            # Membrane contact gammas
            m_direct = direct_indicator * self.membrane_direct_gamma[J_index[2], J_index[3]]
            m_water_mediated = water_indicator * self.membrane_water_gamma[J_index[2], J_index[3]]
            m_protein_mediated = protein_indicator * self.membrane_protein_gamma[J_index[2], J_index[3]]
            contact_energy_membrane = p.k_contact * np.array([m_direct, m_water_mediated, m_protein_mediated]) * sequence_mask_contact[np.newaxis, :, :, np.newaxis, np.newaxis]

            # alpha_ij blending: (1-alpha_ij)*water + alpha_ij*membrane
            alpha_ij = self.alpha[:, np.newaxis] * self.alpha[np.newaxis, :]  # (N, N)
            alpha_ij_4d = alpha_ij[np.newaxis, :, :, np.newaxis, np.newaxis]
            contact_energy = (1 - alpha_ij_4d) * contact_energy_water + alpha_ij_4d * contact_energy_membrane
        else:
            contact_energy = contact_energy_water

        # Electrostatics
        if p.k_electrostatics != 0:
            electrostatics_mask = frustration.compute_mask(self.distance_matrix, maximum_contact_distance=None, minimum_sequence_separation=p.min_sequence_separation_electrostatics, chain_breaks=self.chain_breaks)
            charges = np.array([0, 1, 0, -1, 0, 0, -1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0])
            charges2 = charges[:, np.newaxis] * charges[np.newaxis, :]
            electrostatics_indicator = 1 / (self.distance_matrix + 1E-6) * np.exp(-self.distance_matrix / p.electrostatics_screening_length) * electrostatics_mask
            electrostatics_energy = -p.k_electrostatics * (charges2[np.newaxis, np.newaxis, :, :] * electrostatics_indicator[:, :, np.newaxis, np.newaxis])
            contact_energy = np.append(contact_energy, electrostatics_energy[np.newaxis, :, :, :, :], axis=0)

        self.contact_energy = contact_energy
        self.sparse_potts_model = None
        self._elec_data = None

        # Dense Potts model
        self._potts_model = {}
        self._potts_model['h'] = burial_energy.sum(axis=-1)[:, self.aa_map_awsem_list]
        if p.membrane:
            if p.zim is not None:
                # Preassigned membrane zim is position-dependent and independent of amino acid type.
                self._potts_model['h'] += p.k_membrane * self.dgwoct[:, np.newaxis] * self.phi_z[:, np.newaxis]
            else:
                zim_h = p.k_membrane * self._dgwoct_scale[np.newaxis, :] * self.phi_z[:, np.newaxis]  # (N, 20)
                self._potts_model['h'] += zim_h[:, self.aa_map_awsem_list]
        self._potts_model['J'] = contact_energy.sum(axis=0)[:, :, self.aa_map_awsem_x, self.aa_map_awsem_y]
        self._potts_model['h'][:, 0] = 0
        self._potts_model['J'][:, :, 0, :] = 0
        self._potts_model['J'][:, :, :, 0] = 0
        self._native_energy = None

        # Indicator exposure
        if expose:
            self._start_indicator_exposure(p)
            if p.membrane:
                alpha_ij_2d = self.alpha[:, np.newaxis] * self.alpha[np.newaxis, :]
                # Water pairwise indicators (multiplied by 1-alpha_ij)
                self.indicators.append((1 - alpha_ij_2d) * direct_indicator[:, :, 0, 0] * sequence_mask_contact)
                self.indicators.append((1 - alpha_ij_2d) * protein_indicator[:, :, 0, 0] * sequence_mask_contact)
                self.indicators.append((1 - alpha_ij_2d) * water_indicator[:, :, 0, 0] * sequence_mask_contact)
                # Membrane pairwise indicators (multiplied by alpha_ij)
                self.indicators.append(alpha_ij_2d * direct_indicator[:, :, 0, 0] * sequence_mask_contact)
                self.indicators.append(alpha_ij_2d * protein_indicator[:, :, 0, 0] * sequence_mask_contact)
                self.indicators.append(alpha_ij_2d * water_indicator[:, :, 0, 0] * sequence_mask_contact)
            else:
                self.indicators.append(direct_indicator[:, :, 0, 0] * sequence_mask_contact)
                self.indicators.append(protein_indicator[:, :, 0, 0] * sequence_mask_contact)
                self.indicators.append(water_indicator[:, :, 0, 0] * sequence_mask_contact)
            self.indicator_contact_i = None
            self.indicator_contact_j = None
            self.burial_indicator = self._burial_indicator
            self.direct_indicator = direct_indicator
            self.water_indicator = water_indicator
            self.protein_indicator = protein_indicator
            if p.k_electrostatics != 0:
                self.indicators.append(electrostatics_indicator)
                temp_gamma = 0.5 * p.k_electrostatics * charges2[self.aa_map_awsem_x, self.aa_map_awsem_y]
                temp_gamma[0, :] = 0
                temp_gamma[:, 0] = 0
                self.gamma_array.append(temp_gamma)

    def _build_sparse(self, p, sequence_mask_contact, theta, thetaII, burial_energy, expose):
        """Build sparse Potts model storing couplings only at contact positions."""
        sigma_water = self._sigma_water
        sigma_protein = self._sigma_protein
        ci, cj = np.where(sequence_mask_contact)

        # Scalar indicators at contact pairs
        theta_c = theta[ci, cj]
        thetaII_c = thetaII[ci, cj]
        sigma_water_c = sigma_water[ci, cj]
        sigma_protein_c = sigma_protein[ci, cj]

        dg21 = self.direct_gamma[self.aa_map_awsem_x, self.aa_map_awsem_y]
        wg21 = self.water_gamma[self.aa_map_awsem_x, self.aa_map_awsem_y]
        pg21 = self.protein_gamma[self.aa_map_awsem_x, self.aa_map_awsem_y]
        dg21[0, :] = 0; dg21[:, 0] = 0
        wg21[0, :] = 0; wg21[:, 0] = 0
        pg21[0, :] = 0; pg21[:, 0] = 0

        # Build J_sparse directly in DCA 21-letter alphabet: (N_c, 21, 21)
        J_water = p.k_contact * (
            dg21[np.newaxis, :, :] * theta_c[:, np.newaxis, np.newaxis]
            + wg21[np.newaxis, :, :] * (thetaII_c * sigma_water_c)[:, np.newaxis, np.newaxis]
            + pg21[np.newaxis, :, :] * (thetaII_c * sigma_protein_c)[:, np.newaxis, np.newaxis]
        )

        if p.membrane:
            mdg21 = self.membrane_direct_gamma[self.aa_map_awsem_x, self.aa_map_awsem_y]
            mwg21 = self.membrane_water_gamma[self.aa_map_awsem_x, self.aa_map_awsem_y]
            mpg21 = self.membrane_protein_gamma[self.aa_map_awsem_x, self.aa_map_awsem_y]
            mdg21[0, :] = 0; mdg21[:, 0] = 0
            mwg21[0, :] = 0; mwg21[:, 0] = 0
            mpg21[0, :] = 0; mpg21[:, 0] = 0

            J_membrane = p.k_contact * (
                mdg21[np.newaxis, :, :] * theta_c[:, np.newaxis, np.newaxis]
                + mwg21[np.newaxis, :, :] * (thetaII_c * sigma_water_c)[:, np.newaxis, np.newaxis]
                + mpg21[np.newaxis, :, :] * (thetaII_c * sigma_protein_c)[:, np.newaxis, np.newaxis]
            )

            alpha_ij = (self.alpha[ci] * self.alpha[cj])[:, np.newaxis, np.newaxis]
            J_sparse_21 = (1 - alpha_ij) * J_water + alpha_ij * J_membrane
        else:
            J_sparse_21 = J_water

        # Sparse Potts model
        h = burial_energy.sum(axis=-1)[:, self.aa_map_awsem_list]
        if p.membrane:
            if p.zim is not None:
                # Preassigned membrane zim is position-dependent and independent of amino acid type.
                h += p.k_membrane * self.dgwoct[:, np.newaxis] * self.phi_z[:, np.newaxis]
            else:
                zim_h = p.k_membrane * self._dgwoct_scale[np.newaxis, :] * self.phi_z[:, np.newaxis]
                h += zim_h[:, self.aa_map_awsem_list]
        h[:, 0] = 0
        self.sparse_potts_model = {
            'h': h,
            'J': J_sparse_21,
            'contact_i': ci.astype(np.intp),
            'contact_j': cj.astype(np.intp),
            'L': self.N,
        }
        self._potts_model = {'h': h, 'J': None}
        self._native_energy = None
        self.contact_energy = None

        # Electrostatics
        if p.k_electrostatics != 0:
            self._elec_data = frustration.build_elec_data(
                self.distance_matrix, self.mask, self.sequence,
                self.sparse_potts_model,
                p.k_electrostatics, p.electrostatics_screening_length,
                p.min_sequence_separation_electrostatics,
                chain_breaks=self.chain_breaks,
            )
        else:
            self._elec_data = None

        # Indicator exposure
        if expose:
            self._start_indicator_exposure(p)
            # Always expose dense (L, L) indicators for optimization compatibility
            L = self.N
            dense_theta = np.zeros((L, L))
            dense_theta[ci, cj] = theta_c
            dense_protein = np.zeros((L, L))
            dense_protein[ci, cj] = thetaII_c * sigma_protein_c
            dense_water = np.zeros((L, L))
            dense_water[ci, cj] = thetaII_c * sigma_water_c
            if p.membrane:
                alpha_ij_dense = np.zeros((L, L))
                alpha_ij_dense[ci, cj] = self.alpha[ci] * self.alpha[cj]
                # Water pairwise (multiplied by 1-alpha_ij)
                self.indicators.append((1 - alpha_ij_dense) * dense_theta)
                self.indicators.append((1 - alpha_ij_dense) * dense_protein)
                self.indicators.append((1 - alpha_ij_dense) * dense_water)
                # Membrane pairwise (multiplied by alpha_ij)
                self.indicators.append(alpha_ij_dense * dense_theta)
                self.indicators.append(alpha_ij_dense * dense_protein)
                self.indicators.append(alpha_ij_dense * dense_water)
            else:
                self.indicators.append(dense_theta)
                self.indicators.append(dense_protein)
                self.indicators.append(dense_water)
            self.indicator_contact_i = None
            self.indicator_contact_j = None
            if p.k_electrostatics != 0:
                electrostatics_mask = frustration.compute_mask(
                    self.distance_matrix, maximum_contact_distance=None,
                    minimum_sequence_separation=p.min_sequence_separation_electrostatics,
                    chain_breaks=self.chain_breaks)
                electrostatics_indicator = (1 / (self.distance_matrix + 1E-6)
                                            * np.exp(-self.distance_matrix / p.electrostatics_screening_length)
                                            * electrostatics_mask)
                charges = np.array([0, 1, 0, -1, 0, 0, -1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0])
                charges2 = charges[:, np.newaxis] * charges[np.newaxis, :]
                self.indicators.append(electrostatics_indicator)
                temp_gamma = 0.5 * p.k_electrostatics * charges2[self.aa_map_awsem_x, self.aa_map_awsem_y]
                temp_gamma[0, :] = 0
                temp_gamma[:, 0] = 0
                self.gamma_array.append(temp_gamma)

    def _build_sparse_from_contacts(self, p, ci, cj, theta_c, thetaII_c,
                                     sigma_water_c, sigma_protein_c, burial_energy, expose):
        """Build sparse Potts model from pre-computed contact-level values (sparse distance path)."""
        # Pre-map gamma matrices to DCA 21-letter alphabet (21, 21) to avoid
        # allocating the intermediate (N_c, 20, 20) tensor.
        dg21 = self.direct_gamma[self.aa_map_awsem_x, self.aa_map_awsem_y]
        wg21 = self.water_gamma[self.aa_map_awsem_x, self.aa_map_awsem_y]
        pg21 = self.protein_gamma[self.aa_map_awsem_x, self.aa_map_awsem_y]
        dg21[0, :] = 0; dg21[:, 0] = 0
        wg21[0, :] = 0; wg21[:, 0] = 0
        pg21[0, :] = 0; pg21[:, 0] = 0

        # Build J_sparse directly in DCA 21-letter alphabet: (N_c, 21, 21)
        J_water = p.k_contact * (
            dg21[np.newaxis, :, :] * theta_c[:, np.newaxis, np.newaxis]
            + wg21[np.newaxis, :, :] * (thetaII_c * sigma_water_c)[:, np.newaxis, np.newaxis]
            + pg21[np.newaxis, :, :] * (thetaII_c * sigma_protein_c)[:, np.newaxis, np.newaxis]
        )

        if p.membrane:
            # Membrane gamma matrices in 21-letter alphabet
            mdg21 = self.membrane_direct_gamma[self.aa_map_awsem_x, self.aa_map_awsem_y]
            mwg21 = self.membrane_water_gamma[self.aa_map_awsem_x, self.aa_map_awsem_y]
            mpg21 = self.membrane_protein_gamma[self.aa_map_awsem_x, self.aa_map_awsem_y]
            mdg21[0, :] = 0; mdg21[:, 0] = 0
            mwg21[0, :] = 0; mwg21[:, 0] = 0
            mpg21[0, :] = 0; mpg21[:, 0] = 0

            J_membrane = p.k_contact * (
                mdg21[np.newaxis, :, :] * theta_c[:, np.newaxis, np.newaxis]
                + mwg21[np.newaxis, :, :] * (thetaII_c * sigma_water_c)[:, np.newaxis, np.newaxis]
                + mpg21[np.newaxis, :, :] * (thetaII_c * sigma_protein_c)[:, np.newaxis, np.newaxis]
            )

            # alpha_ij at contact positions
            alpha_ij = (self.alpha[ci] * self.alpha[cj])[:, np.newaxis, np.newaxis]
            J_sparse_21 = (1 - alpha_ij) * J_water + alpha_ij * J_membrane
        else:
            J_sparse_21 = J_water

        # Sparse Potts model
        h = burial_energy.sum(axis=-1)[:, self.aa_map_awsem_list]
        if p.membrane:
            # Add Zim membrane potential: k_membrane * DGwoct(aa_type) * phi_z(position)
            if p.zim is not None:
                # Preassigned membrane zim is position-dependent and independent of amino acid type.
                h += p.k_membrane * self.dgwoct[:, np.newaxis] * self.phi_z[:, np.newaxis]
            else:
                zim_h = p.k_membrane * self._dgwoct_scale[np.newaxis, :] * self.phi_z[:, np.newaxis]  # (N, 20)
                h += zim_h[:, self.aa_map_awsem_list]
        h[:, 0] = 0
        self.sparse_potts_model = {
            'h': h,
            'J': J_sparse_21,
            'contact_i': ci.astype(np.intp),
            'contact_j': cj.astype(np.intp),
            'L': self.N,
        }
        self._potts_model = {'h': h, 'J': None}
        self._native_energy = None
        self.contact_energy = None

        # Electrostatics (from sparse 40Å distance data)
        if p.k_electrostatics != 0:
            self._elec_data = frustration.build_elec_data_sparse(
                self._sparse_distance_matrix_elec,
                self.mask,
                self.sequence, self.sparse_potts_model,
                p.k_electrostatics, p.electrostatics_screening_length,
                p.min_sequence_separation_electrostatics,
                chain_breaks=self.chain_breaks,
                mask_sequence_cutoff=self.sequence_cutoff if self.distance_cutoff is None else None,
                mask_chain_breaks=self.chain_breaks if self.distance_cutoff is None else None,
            )
        else:
            self._elec_data = None

        # Indicator exposure
        if expose:
            self._start_indicator_exposure(p)
            L = self.N
            dense_theta = np.zeros((L, L))
            dense_theta[ci, cj] = theta_c
            dense_protein = np.zeros((L, L))
            dense_protein[ci, cj] = thetaII_c * sigma_protein_c
            dense_water = np.zeros((L, L))
            dense_water[ci, cj] = thetaII_c * sigma_water_c
            if p.membrane:
                alpha_ij_dense = np.zeros((L, L))
                alpha_ij_dense[ci, cj] = self.alpha[ci] * self.alpha[cj]
                self.indicators.append((1 - alpha_ij_dense) * dense_theta)
                self.indicators.append((1 - alpha_ij_dense) * dense_protein)
                self.indicators.append((1 - alpha_ij_dense) * dense_water)
                self.indicators.append(alpha_ij_dense * dense_theta)
                self.indicators.append(alpha_ij_dense * dense_protein)
                self.indicators.append(alpha_ij_dense * dense_water)
            else:
                self.indicators.append(dense_theta)
                self.indicators.append(dense_protein)
                self.indicators.append(dense_water)
            self.indicator_contact_i = None
            self.indicator_contact_j = None
            if p.k_electrostatics != 0:
                # Reconstruct dense electrostatics indicator from sparse 40Å data
                elec_dm = self._sparse_distance_matrix_elec
                e_mask = frustration.compute_mask_sparse(
                    elec_dm.row, elec_dm.col, elec_dm.data, elec_dm.shape,
                    maximum_contact_distance=None,
                    minimum_sequence_separation=p.min_sequence_separation_electrostatics,
                    chain_breaks=self.chain_breaks)
                e_dists = elec_dm.lookup(e_mask.row, e_mask.col)
                electrostatics_indicator = np.zeros((L, L))
                with np.errstate(divide='ignore', invalid='ignore'):
                    vals = np.exp(-e_dists / p.electrostatics_screening_length) / e_dists
                    vals[np.isnan(vals)] = 0.0
                    vals[np.isinf(vals)] = 0.0
                electrostatics_indicator[e_mask.row, e_mask.col] = vals
                charges = np.array([0, 1, 0, -1, 0, 0, -1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0])
                charges2 = charges[:, np.newaxis] * charges[np.newaxis, :]
                self.indicators.append(electrostatics_indicator)
                temp_gamma = 0.5 * p.k_electrostatics * charges2[self.aa_map_awsem_x, self.aa_map_awsem_y]
                temp_gamma[0, :] = 0
                temp_gamma[:, 0] = 0
                self.gamma_array.append(temp_gamma)

    def _get_configurational_contact_data(self):
        """Extract upper-triangle contact distances and indices for configurational frustration.

        Works for both sparse and dense distance matrices.

        Returns
        -------
        distances : np.ndarray (C,)
            Contact distances (upper triangle, within distance_cutoff_contact).
        indices1 : np.ndarray (C,)
            Row indices of contacts.
        indices2 : np.ndarray (C,)
            Column indices of contacts.
        """
        if self._distance_is_sparse:
            dm = self._sparse_distance_matrix
            # Upper triangle: row < col
            upper = dm.row < dm.col
            uci = dm.row[upper]
            ucj = dm.col[upper]
            udists = dm.data[upper]
            valid = (udists < self.distance_cutoff_contact) & (udists > 0)
            return udists[valid], uci[valid], ucj[valid]
        else:
            dm = self.distance_matrix
            n = dm.shape[0]
            tri_upper_indices = np.triu_indices(n, k=1)
            tri_dists = dm[tri_upper_indices]
            valid = (tri_dists < self.distance_cutoff_contact) & (tri_dists > 0)
            return tri_dists[valid], tri_upper_indices[0][valid], tri_upper_indices[1][valid]

    def _compute_sigma_at_pairs(self, n1, n2):
        """Compute sigma_water and sigma_protein at specific residue pairs.

        Uses pre-computed dense sigma if available, otherwise computes from rho_r.
        """
        if self._sigma_water is not None:
            return self._sigma_water[n1, n2], self._sigma_protein[n1, n2]
        # Sparse mode: compute from rho_r
        rho1 = self.rho_r[n1]
        rho2 = self.rho_r[n2]
        sw = 0.25 * (1 - np.tanh(self.eta_sigma * (rho1 - self.rho_0))) * (1 - np.tanh(self.eta_sigma * (rho2 - self.rho_0)))
        return sw, 1 - sw

    def compute_configurational_decoy_statistics(self, n_decoys=4000,aa_freq=None):
        # ['A', 'R', 'N', 'D', 'C', 'Q', 'E', 'G', 'H', 'I', 'L', 'K', 'M', 'F', 'P', 'S', 'T', 'W', 'Y', 'V']
        _AA='ARNDCQEGHILKMFPSTWYV'
        if aa_freq is None:
            seq_index = np.array([_AA.find(aa) for aa in self.sequence])
            N=self.N
        else:
            N=self.N*10
            total = sum(aa_freq)
            probabilities = [freq / total for freq in aa_freq.ravel()]
            seq_index = np.random.choice(a=len(aa_freq), size=N, p=probabilities)
        
        distances, _, _ = self._get_configurational_contact_data()

        burial_indicator = self._burial_indicator

        #Calculate theta and indicators
        theta = 0.25 * (1 + np.tanh(self.eta * (distances - self.r_min))) * (1 + np.tanh(self.eta * (self.r_max - distances))) # (c,)
        thetaII = 0.25 * (1 + np.tanh(self.eta * (distances - self.r_minII))) * (1 + np.tanh(self.eta * (self.r_maxII - distances))) #(c,)
           
        charges = np.array([0, 1, 0, -1, 0, 0, -1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0])
        electrostatics_indicator = np.exp(-distances / self.electrostatics_screening_length) / distances

        decoy_energies=np.zeros(n_decoys)
        for i in range(n_decoys):
            c=np.random.randint(0,len(distances))
            n1=np.random.randint(0,self.N)
            n2=np.random.randint(0,self.N)
            qi1=np.random.randint(0,N)
            qi2=np.random.randint(0,N)
            q1=seq_index[qi1]
            q2=seq_index[qi2]

            
            burial_energy1 = (-0.5 * self.k_contact * self.burial_gamma[q1] * burial_indicator[n1]).sum(axis=0)
            burial_energy2 = (-0.5 * self.k_contact * self.burial_gamma[q2] * burial_indicator[n2]).sum(axis=0)
            if self.alpha is not None:
                # Blend burial with membrane gamma
                m_burial1 = (-0.5 * self.k_contact * self.membrane_burial_gamma[q1] * burial_indicator[n1]).sum(axis=0)
                m_burial2 = (-0.5 * self.k_contact * self.membrane_burial_gamma[q2] * burial_indicator[n2]).sum(axis=0)
                burial_energy1 = (1 - self.alpha[n1]) * burial_energy1 + self.alpha[n1] * m_burial1
                burial_energy2 = (1 - self.alpha[n2]) * burial_energy2 + self.alpha[n2] * m_burial2
                # Zim membrane potential
                burial_energy1 += self.k_membrane * self._dgwoct_scale[q1] * self.phi_z[n1]
                burial_energy2 += self.k_membrane * self._dgwoct_scale[q2] * self.phi_z[n2]
            
            sigma_water_val, sigma_protein_val = self._compute_sigma_at_pairs(n1, n2)
            direct = theta[c] * self.direct_gamma[q1, q2]
            water_mediated = sigma_water_val * thetaII[c] * self.water_gamma[q1,q2]
            protein_mediated = sigma_protein_val * thetaII[c] * self.protein_gamma[q1,q2]
            contact_energy = -self.k_contact * (direct+water_mediated+protein_mediated)
            if self.alpha is not None:
                # Blend contact with membrane gamma
                m_direct = theta[c] * self.membrane_direct_gamma[q1, q2]
                m_water = sigma_water_val * thetaII[c] * self.membrane_water_gamma[q1, q2]
                m_protein = sigma_protein_val * thetaII[c] * self.membrane_protein_gamma[q1, q2]
                m_contact = -self.k_contact * (m_direct + m_water + m_protein)
                alpha_ij = self.alpha[n1] * self.alpha[n2]
                contact_energy = (1 - alpha_ij) * contact_energy + alpha_ij * m_contact
            electrostatics_energy = self.k_electrostatics * electrostatics_indicator[c]*charges[q1]*charges[q2]

            decoy_energies[i]=(burial_energy1+burial_energy2+contact_energy+electrostatics_energy)
            
        mean_decoy_energy = np.mean(decoy_energies)
        std_decoy_energy = np.std(decoy_energies)
        return mean_decoy_energy, std_decoy_energy
    
    def compute_configurational_energies(self):
        _AA='ARNDCQEGHILKMFPSTWYV'
        seq_index = np.array([_AA.find(aa) for aa in self.sequence])
        distances, indices1, indices2 = self._get_configurational_contact_data()
        n_contacts=len(distances)
        n = self.N

        burial_indicator = self._burial_indicator

        #Calculate theta and indicators
        theta = 0.25 * (1 + np.tanh(self.eta * (distances - self.r_min))) * (1 + np.tanh(self.eta * (self.r_max - distances))) # (c,)
        thetaII = 0.25 * (1 + np.tanh(self.eta * (distances - self.r_minII))) * (1 + np.tanh(self.eta * (self.r_maxII - distances))) #(c,)
           
        charges = np.array([0, 1, 0, -1, 0, 0, -1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0])
        electrostatics_indicator = np.exp(-distances / self.electrostatics_screening_length) / distances

        configurational_energies=np.full((n,n), np.nan) # masked pairs will be left as nan
        for c in range(n_contacts):
            n1=indices1[c]
            n2=indices2[c]
            q1=seq_index[n1]
            q2=seq_index[n2]

            burial_energy1 = (-0.5 * self.k_contact * self.burial_gamma[q1] * burial_indicator[n1]).sum(axis=0)
            burial_energy2 = (-0.5 * self.k_contact * self.burial_gamma[q2] * burial_indicator[n2]).sum(axis=0)
            if self.alpha is not None:
                m_burial1 = (-0.5 * self.k_contact * self.membrane_burial_gamma[q1] * burial_indicator[n1]).sum(axis=0)
                m_burial2 = (-0.5 * self.k_contact * self.membrane_burial_gamma[q2] * burial_indicator[n2]).sum(axis=0)
                burial_energy1 = (1 - self.alpha[n1]) * burial_energy1 + self.alpha[n1] * m_burial1
                burial_energy2 = (1 - self.alpha[n2]) * burial_energy2 + self.alpha[n2] * m_burial2
                burial_energy1 += self.k_membrane * self._dgwoct_scale[q1] * self.phi_z[n1]
                burial_energy2 += self.k_membrane * self._dgwoct_scale[q2] * self.phi_z[n2]
            
            sigma_water_val, sigma_protein_val = self._compute_sigma_at_pairs(n1, n2)
            direct = theta[c] * self.direct_gamma[q1, q2]
            water_mediated = sigma_water_val * thetaII[c] * self.water_gamma[q1,q2]
            protein_mediated = sigma_protein_val * thetaII[c] * self.protein_gamma[q1,q2]
            contact_energy = -self.k_contact * (direct+water_mediated+protein_mediated)
            if self.alpha is not None:
                m_direct = theta[c] * self.membrane_direct_gamma[q1, q2]
                m_water = sigma_water_val * thetaII[c] * self.membrane_water_gamma[q1, q2]
                m_protein = sigma_protein_val * thetaII[c] * self.membrane_protein_gamma[q1, q2]
                m_contact = -self.k_contact * (m_direct + m_water + m_protein)
                alpha_ij = self.alpha[n1] * self.alpha[n2]
                contact_energy = (1 - alpha_ij) * contact_energy + alpha_ij * m_contact
            electrostatics_energy = self.k_electrostatics * electrostatics_indicator[c]*charges[q1]*charges[q2]

            energy=(burial_energy1+burial_energy2+contact_energy+electrostatics_energy)
            configurational_energies[n1,n2]=energy
            configurational_energies[n2,n1]=energy
            # decoy_data+=[[c, n1, n2, q1, q2, _AA[q1],_AA[q2], distances[c], self.rho_r[n1], self.rho_r[n2], contact_energy/4.184, burial_energy1/4.184, burial_energy2/4.184, electrostatics_energy/4.184, energy/4.184]]
        # import pandas as pd
        return configurational_energies #, pd.DataFrame(decoy_data, columns=decoy_data_columns)
    
    def configurational_frustration(self,aa_freq=None, correction=0, n_decoys=4000):
        mean_decoy_energy, std_decoy_energy = self.compute_configurational_decoy_statistics(n_decoys=n_decoys,aa_freq=aa_freq)
        return -(self.compute_configurational_energies()-mean_decoy_energy)/(std_decoy_energy+correction)
